TargetServer = args[0];
MoneyThresh = 0.55;

tMaxMoney = getServerMaxMoney(TargetServer);
tCurMoney = getServerMoneyAvailable(TargetServer);
tSMoneyPct = tCurMoney / tMaxMoney;
print("Cur Money Pct: ", tSMoneyPct) ;

tMinSecLvl = getServerMinSecurityLevel(TargetServer);
tCurSecLvl = getServerSecurityLevel(TargetServer);

while(true)
{
	if(tCurSecLvl > (tMinSecLvl * 1.1))
	{
		// Weaken Subsection
		tCurSecLvl = getServerSecurityLevel(TargetServer);
		print("Need to Weaken Security: ", tCurSecLvl, "/", tMinSecLvl, " ", tCurSecLvl/tMinSecLvl);
		weaken(TargetServer);
	}
	else if(tSMoneyPct < MoneyThresh)
	{
		// Grow Subsection
		tCurMoney = getServerMoneyAvailable(TargetServer);
		tSMoneyPct = tCurMoney / tMaxMoney;
		print("Money Available: ", tCurMoney, "/", tMaxMoney, " ", tSMoneyPct);

		grow(TargetServer);
	}
	else
	{
		hack(TargetServer);
	}
}